// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/bwmarrin/snowflake"
	"github.com/gofiber/fiber/v3"
	"github.com/google/wire"
	"url_shortener/internal/config"
	"url_shortener/internal/controller"
	"url_shortener/internal/database"
	"url_shortener/internal/exeption"
	"url_shortener/internal/repository"
	"url_shortener/internal/router"
	"url_shortener/internal/service"
	"url_shortener/pkg/utils"
	"url_shortener/pkg/validator"
)

// Injectors from wire.go:

// InitializeServer initializes the Fiber application with all dependencies injected.
func InitializeServer() (*fiber.App, func(), error) {
	config, err := provideConfig()
	if err != nil {
		return nil, nil, err
	}
	pool, cleanup, err := database.NewPostgresPool(config)
	if err != nil {
		return nil, nil, err
	}
	client, cleanup2, err := database.NewRedisClient(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	linkRepository := repository.NewLinkRepository(pool, client)
	node, err := provideSnowflakeNode(config)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	linkService := service.NewLinkService(config, linkRepository, node)
	customValidator := validator.NewValidator()
	linkController := controller.NewLinkController(linkService, customValidator)
	healthController := controller.NewHealthController()
	app := provideFiberApp(linkController, healthController)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func provideSnowflakeNode(cfg *config.Config) (*snowflake.Node, error) {
	return utils.NewSnowflakeNode(cfg.NodeID)
}

func provideConfig() (*config.Config, error) {
	return config.LoadConfig()
}

func provideFiberApp(
	linkCtrl controller.LinkController,
	healthCtrl controller.HealthController,
) *fiber.App {
	app := fiber.New(fiber.Config{
		AppName:      "High-Performance URL Shortener",
		ErrorHandler: exeption.ErrorHandler,
	})
	router.SetupRouter(app, linkCtrl, healthCtrl)

	return app
}

var serverSet = wire.NewSet(
	provideConfig, database.NewPostgresPool, database.NewRedisClient, provideSnowflakeNode, validator.NewValidator, repository.NewLinkRepository, service.NewLinkService, controller.NewLinkController, controller.NewHealthController, provideFiberApp,
)
