// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/bwmarrin/snowflake"
	"github.com/gofiber/fiber/v3"
	"github.com/google/wire"
	"url_shortener/internal/analytics"
	"url_shortener/internal/config"
	"url_shortener/internal/controller"
	"url_shortener/internal/database"
	"url_shortener/internal/exeption"
	"url_shortener/internal/repository"
	"url_shortener/internal/router"
	"url_shortener/internal/service"
	"url_shortener/pkg/utils"
	"url_shortener/pkg/validator"
)

// Injectors from wire.go:

// InitializeServer initializes the Fiber application with all dependencies injected.
func InitializeServer() (*fiber.App, func(), error) {
	config, err := provideConfig()
	if err != nil {
		return nil, nil, err
	}
	db, cleanup, err := database.NewGormDB(config)
	if err != nil {
		return nil, nil, err
	}
	client, cleanup2, err := database.NewRedisClient(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	linkRepository := repository.NewLinkRepository(db, client)
	node, err := provideSnowflakeNode(config)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	workerPool, cleanup3, err := provideWorkerPool(linkRepository)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	linkService := service.NewLinkService(config, linkRepository, node, workerPool)
	customValidator := validator.NewValidator()
	linkController := controller.NewLinkController(linkService, customValidator)
	userRepository := repository.NewUserRepository(db)
	authService := service.NewAuthService(config, userRepository)
	authController := controller.NewAuthController(authService, customValidator)
	healthController := controller.NewHealthController()
	app := provideFiberApp(config, linkController, authController, healthController)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func provideSnowflakeNode(cfg *config.Config) (*snowflake.Node, error) {
	return utils.NewSnowflakeNode(cfg.NodeID)
}

func provideConfig() (*config.Config, error) {
	return config.LoadConfig()
}

func provideWorkerPool(repo repository.LinkRepository) (analytics.WorkerPool, func(), error) {
	wp := analytics.NewWorkerPool(repo, analytics.DefaultConfig())
	wp.Start()
	cleanup := func() {
		wp.Stop()
	}
	return wp, cleanup, nil
}

func provideFiberApp(
	cfg *config.Config,
	linkCtrl controller.LinkController,
	authCtrl controller.AuthController,
	healthCtrl controller.HealthController,
) *fiber.App {
	app := fiber.New(fiber.Config{
		AppName:      "High-Performance URL Shortener",
		ErrorHandler: exeption.ErrorHandler,
	})
	router.SetupRouter(app, linkCtrl, authCtrl, healthCtrl, cfg.JWT.Secret)

	return app
}

var serverSet = wire.NewSet(
	provideConfig, database.NewGormDB, database.NewRedisClient, provideSnowflakeNode, validator.NewValidator, repository.NewLinkRepository, repository.NewUserRepository, provideWorkerPool, service.NewLinkService, service.NewAuthService, controller.NewLinkController, controller.NewAuthController, controller.NewHealthController, provideFiberApp,
)
